### ISSUE TITLE
Add support for parallel streaming of responses

### ISSUE THREAD

**Issue by denk0403** [denk0403/TintAPI2#2]
- [ ] Stream test execution output as [JSON lines](https://jsonlines.org/).
  - [ ] Ensure memory usage remains low.
- [ ] Increase max step count.
- [ ] Investigate parallelizing test execution.
  - [ ] [Goroutines and Channels](https://www.golang-book.com/books/intro/10)?
  - [ ] [`sync.WaitGroup{}`](https://pkg.go.dev/sync#WaitGroup)

# Goal

Support executing the following machine:
```yaml
start: a
accept: accept
reject: reject

transitions:
- [a, _, b, 1, R]
- [b, _, c, 1, R]
- [c, _, d, 1, R]
- [d, _, a, 1, L]
- [e, _, accept, 1, R]
- [a, 1, c, 1, L]
- [b, 1, b, 1, R]
- [c, 1, e, _, L]
- [d, 1, d, 1, L]
- [e, 1, a, _, L]
```

Current behavior: 
```
Error: This test took too long or encountered an infinite loop.
Skipping this test.
```
